### ISSUE TITLE
Issue when using the dotnet-new command

### ISSUE THREAD

**Issue by carlosagsmendes** [ServiceStack/servicestack-cli#1]
Hi, 

I was trying this but I get an error when executing `dotnet-new`

```
env: node\r: No such file or directory
```

I'm using node v8.9.3

**Comment by mythz** [comment]
Which OS? do you have a more complete log available?

And can you confirm that you installed it with:

    $ npm install -g @servicestack/cli

Can you also try uninstalling any previous versions:

    $ npm uninstall -g servicestack-cli
    $ npm uninstall -g @servicestack/cli

**Comment by mythz** [comment]
I've installed `@servicestack/cli` and verified that `dotnet-new` works in:

 - Windows 10
 - Ubuntu using WSL on Windows 10
 - OSX
 - Ubuntu 16.04

So it doesn't look like there's an issue with the package.

**Comment by carlosagsmendes** [comment]
Thank you. I'm using High Sierra 10.3.2

I've found a similar error in another library online. In their case was related to [line ending](https://github.com/Azure/iothub-explorer/issues/6)

If you can think of any way to get detailed logs please let me know.

**Comment by labilbe** [comment]
Hi, I encounter same probem with Ubuntu (native) 18.04.2 LTS

```
franck@PAEZ:~/Projects/console$ npm -v
3.5.2
```
```
franck@PAEZ:~/Projects/console$ node -v
v8.10.0
```
Error is:
```
franck@PAEZ:~/Projects/console$ dotnet-new
/usr/bin/env: ‘node\r’: No such file or directory
```

I tried uninstalling and installing again as mythz suggested but error is still here.

**Comment by mythz** [comment]
@labilbe I've uninstalled and re-installed the latest version:

    $ npm uninstall @servicestack/cli
    $ npm i -g @servicestack/cli

Which runs without issue in Ubuntu 16.04 (native) without issue:

```
$ dotnet-new -v
Version: 1.0.7
```

If you're still have issues you can also create projects with the [latest `web` .NET Core tool](https://github.com/NetFrameworkCoreTemplates/web-corefx#web-corefx):

    $ dotnet tool install -g web

Which lets you use `web new` as an alternative to the `dotnet-new` npm tool, e.g:

    $ web new vue-spa ProjectName

Or view all available templates with:

    $ web new

**Comment by labilbe** [comment]
I still have same problem with `dotnet-new`.
I tried re-installing DotNet Core and the problem stills.
But your workaround using `web new` works now like a charm.
Thank you for your time.
