### ISSUE TITLE
dotnet-new behind a proxy

### ISSUE THREAD

**Issue by stephanharmse** [ServiceStack/servicestack-cli#3]
How does one use dotnet-new if you are located behind a proxy (in for example a corporate environment)?

**Comment by mythz** [comment]
It requires a direct internet connection so you couldn't use it behind a proxy. You'd need to download the project template directly from GitHub: http://docs.servicestack.net/templates-single-page-apps#net-core-21

Then download it as a .zip

![image001](https://user-images.githubusercontent.com/89361/44925360-3aae6f80-ad1c-11e8-9fd5-e1fef6fa783a.png)
