### ISSUE TITLE
BaseUrl https protocol is re-written to http on update

### ISSUE THREAD

**Issue by matthew-dean** [ServiceStack/servicestack-cli#4]
I'm using `x typescript` to generate an initial dtos file like:
```
x typescript https://myserver.example.com dtos.ts
```
This works fine. However, it writes a file with a missing `s`:
```
BaseUrl: http://myserver.example.com
```
If I re-write it as `https://myserver.example.com` and save and then write `x typescript`, it updates, but again re-writes it as `http` instead of `https`.

(In our setup, an `http` request will be refused.)

**Comment by mythz** [comment]
This is the BaseUrl that your App thinks it's hosted at which would be returned in the generated DTOs at `/types/typescript`.

So it's not clear why your App thinks it's hosted on a different URL, but you can force it to use a specific URL with:

```csharp
SetConfig(new HostConfig {
    WebHostUrl = "https://myserver.example.com dtos.ts"
})
```

Which you may only want to specify in production or release builds with `#if !DEBUG`.

FYI this isn't the right repo for the x dotnet tool you're using, you can find support options for future support questions at:
https://docs.servicestack.net/#community-support
